import mysql.connector

# Exception Handling

# try:
#     دستورات
# except Exception as e:
#     مدیریت خطا : e

# def test():
#     return 1/0
#
# print("Start")
#
try:
    # a = []
    # print(a[5])
    # print(a)
    test()
except Exception as e:
    print(f"خطا : {e}")

#
# finally:
#     print("Finally")
#
# print("End")